[achievement.practice]
display_name = "Practice Makes Perfect!"
description = "Play a pratice round"
# requirements = false

[achievement.play]
display_name = "For real this time"
description = "Play a scored game round"
# requirements = false

[achievement.playEvery]
display_name = "Spelling jedi"
description = "Play a game for every single topic"
# requirements = false

[achievement.diligence5]
display_name = "Just starting out"
description = "Play 5 Games"
# requirements = { num_games = 5 }

[achievement.diligence10]
display_name = "Getting the hang of it"
description = "Play 10 Games"
# requirements = { num_games = 10 }

[achievement.diligence20]
display_name = "Here we go again"
description = "Play 20 Games"
# requirements = { num_games = 20 }

[achievement.diligence50]
display_name = "Into the breach"
description = "Play 50 Games"
# requirements = { num_games = 50 }

[achievement.diligence100]
display_name = "Mastery achieved"
description = "Play 100 Games"
# requirements = { num_games = 100 }

[achievement.highscore75]
display_name = "On the way up"
description = "Achieve a high score of at least 75 points"
# requirements = { high_score = 75 }

[achievement.highscore90]
display_name = "Reaching the peak"
description = "Achieve a high score of at least 90 points"
# requirements = { high_score = 90 }

[achievement.highscore100]
display_name = "On top of the world"
description = "Achieve a high score of 100 points"
# requirements = { high_score = 100 }

[achievement.unlockAll]
display_name = "Stylish Kiddo"
description = "Unlock all costumes"
# requirements = { costumes = "all" }

[achievement.star10]
display_name = "Small beginnings"
description = "Have 10 stars"
# requirements = { stars = 10 }

[achievement.star50]
display_name = "Climbing the ladder"
description = "Have 50 stars"
# requirements = { stars = 50 }

[achievement.star100]
display_name = "Can't Stop Won't Stop"
description = "Have 100 stars"
# requirements = { stars = 100 }

[achievement.star200]
display_name = "Mr. Moneybags"
description = "Have 200 stars"
# requirements = { stars = 200 }

[achievement.star300]
display_name = "Hello, Jeff Bezos"
description = "Have 300 stars"
# requirements = { stars = 300 }