[global]
img_path = "/static/costume/"

[costume.default]
name = "B"
description = "B, just your average bee with an aptitude for learning"
price = 0

[costume.sailor]
name = "Sailor Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 5

[costume.magician]
name = "Magician Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 30

[costume.wizard]
name = "Wizard Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 5

[costume.ninja]
name = "Ninja Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 100

[costume.queen]
name = "Queen Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 30

[costume.fairy]
name = "Fairy Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 80

[costume.professor]
name = "Professor Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 200

[costume.alien]
name = "Alien Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 50

[costume.chef]
name = "Chef Bee"
description = "Taking a break from blundering the high seas to brush up on his Te Reo"
price = 20
